// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MarkupExtensionTokenDetails.cs" company="Xamlr">
//   The MIT License (MIT)
//   
//    Copyright (c) 2019 Brian Tyler
//   
//   Permission is hereby granted, free of charge, to any person obtaining a copy
//   of this software and associated documentation files (the "Software"), to deal
//   in the Software without restriction, including without limitation the rights
//   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//   copies of the Software, and to permit persons to whom the Software is
//   furnished to do so, subject to the following conditions:
//   
//   The above copyright notice and this permission notice shall be included in
//   all copies or substantial portions of the Software.
//   
//   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//   THE SOFTWARE.
// </copyright>
// <summary>
//   Defines the MarkupExtensionTokenDetails type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace Xamlr.Core.Markup
{
    using System.Diagnostics;

    /// <summary>
    /// Represents additional information about a token generated by a <see cref="MemberNameOrStringTerminal"/> that would
    /// otherwise be lost during parsing.
    /// </summary>
    [DebuggerDisplay("{OriginalValue}, IsQuoted={IsQuoted}")]
    public class MarkupExtensionTokenDetails : IMarkupExtensionTokenDetails
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarkupExtensionTokenDetails"/> class.
        /// </summary>
        /// <param name="originalValue">
        /// The original value.
        /// </param>
        /// <param name="isQuoted">
        /// A value indicating whether the token is quoted.
        /// </param>
        public MarkupExtensionTokenDetails(string originalValue, bool isQuoted)
        {
            this.OriginalValue = originalValue;
            this.IsQuoted = isQuoted;
        }

        /// <summary>
        /// Gets the original value.
        /// </summary>
        public string OriginalValue { get; private set; }

        /// <summary>
        /// Gets a value indicating whether the token is quoted.
        /// </summary>
        public bool IsQuoted { get; private set; }
    }
}